/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOBREITWIGNERTWOBODYPHSPEVTGEN
#define ROOBREITWIGNERTWOBODYPHSPEVTGEN

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooBreitWignerTwoBodyPHSPEvtGen : public RooAbsPdf {
public:
	RooBreitWignerTwoBodyPHSPEvtGen() : cutoff(0), m1(0), m2(0) { };
	RooBreitWignerTwoBodyPHSPEvtGen(const char *name, const char *title,
			RooAbsReal& _m,
			RooAbsReal& _mass_J,
			RooAbsReal& _width_J,
			double _cutoff,
			double _m1,
			double _m2);
	RooBreitWignerTwoBodyPHSPEvtGen(const RooBreitWignerTwoBodyPHSPEvtGen& other, const char* name=0);
	virtual TObject* clone(const char* newname) const {
		return new RooBreitWignerTwoBodyPHSPEvtGen(*this,newname);
	}
	inline virtual ~RooBreitWignerTwoBodyPHSPEvtGen() { };

protected:

	RooRealProxy m;
	RooRealProxy mass_J;
	RooRealProxy width_J;

	// store cutoff value for lower width
	const double cutoff;
	// store inv. mass of 1st decay product
	const double m1;
	// store inv. mass of 2nd decay prodcut
	const double m2;

	Double_t evaluate() const;

private:

	ClassDef(RooBreitWignerTwoBodyPHSPEvtGen,1) // Your description goes here...
};

#endif
