/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOBREITWIGNERTWOBODYPHSP
#define ROOBREITWIGNERTWOBODYPHSP

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooBreitWignerTwoBodyPHSP : public RooAbsPdf {
public:
	RooBreitWignerTwoBodyPHSP() : m1(0), m2(0) { };
	RooBreitWignerTwoBodyPHSP(const char *name, const char *title,
			RooAbsReal& _m,
			RooAbsReal& _mass_J,
			RooAbsReal& _width_J,
			double _m1,
			double _m2);
	RooBreitWignerTwoBodyPHSP(const RooBreitWignerTwoBodyPHSP& other, const char* name=0);
	virtual TObject* clone(const char* newname) const {
		return new RooBreitWignerTwoBodyPHSP(*this,newname);
	}
	inline virtual ~RooBreitWignerTwoBodyPHSP() { };

protected:

	RooRealProxy m;
	RooRealProxy mass_J;
	RooRealProxy width_J;

	// store inv. mass of 1st decay product
	const double m1;
	// store inv. mass of 2nd decay prodcut
	const double m2;

	Double_t evaluate() const;

private:

	ClassDef(RooBreitWignerTwoBodyPHSP,1) // Your description goes here...
};

#endif
