/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROOBIFURSTUDENTSTDISTRIBUTION
#define ROOBIFURSTUDENTSTDISTRIBUTION

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooBifurStudentsTDistribution : public RooAbsPdf {
public:
	RooBifurStudentsTDistribution() {};
	RooBifurStudentsTDistribution(const char *name, const char *title,
			RooAbsReal& _x,
			RooAbsReal& _mu,
			RooAbsReal& _sigma,
			RooAbsReal& _sigma_asym,
			RooAbsReal& _nu_l,
			RooAbsReal& _nu_r);
	RooBifurStudentsTDistribution(const RooBifurStudentsTDistribution& other, const char* name=0);
	virtual TObject* clone(const char* newname) const { return new RooBifurStudentsTDistribution(*this,newname); }
	inline virtual ~RooBifurStudentsTDistribution() { }

protected:

	RooRealProxy x;
	RooRealProxy mu;
	RooRealProxy sigma;
	RooRealProxy sigma_asym;
	RooRealProxy nu_l;
	RooRealProxy nu_r;

	Double_t evaluate() const;

private:

	ClassDef(RooBifurStudentsTDistribution,1) // Your description goes here...
};

#endif
