/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROOCATEGORYPDF
#define ROOCATEGORYPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooCategoryPdf : public RooAbsPdf {
public:
	RooCategoryPdf() {} ;
	RooCategoryPdf(const char *name, const char *title,
			RooAbsCategory& _c);
	RooCategoryPdf(const RooCategoryPdf& other, const char* name=0) ;
	virtual TObject* clone(const char* newname) const { return new RooCategoryPdf(*this,newname); }
	inline virtual ~RooCategoryPdf() { }

	virtual Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const;
	virtual Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const;

protected:

	RooCategoryProxy c;

	Double_t evaluate() const ;

private:

	ClassDef(RooCategoryPdf,1) // Your description goes here...
};

#endif
