/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROOCUTPDF
#define ROOCUTPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooCutPdf : public RooAbsPdf {
public:
	RooCutPdf() : m_cut_value(0.0), m_left_non_zero(true) {} ;
	RooCutPdf(const char *name, const char *title,
			RooAbsReal& _x, double _cut_value, bool _left_non_zero);
	RooCutPdf(const RooCutPdf& other, const char* name=0) ;
	virtual TObject* clone(const char* newname) const { return new RooCutPdf(*this,newname); }
	inline virtual ~RooCutPdf() { }

	virtual Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const;
	virtual Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const;

protected:

	RooRealProxy x ;

	const double m_cut_value;
	const bool m_left_non_zero;

	Double_t evaluate() const ;

private:

	ClassDef(RooCutPdf,1) // Your description goes here...
};

#endif
