/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROODALITZHIST
#define ROODALITZHIST

#include "RooAbsPdf.h"
#include "TH2F.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooDalitzHist : public RooAbsPdf {
public:
	RooDalitzHist() :  hist(NULL), mM(0), m1(0), m2(0), m3(0) {} ;
	RooDalitzHist(const char *name, const char *title,
			RooAbsReal& _m12,
			RooAbsReal& _m23,
            TH2F *_hist,
			double _mM,
			double _m1,
			double _m2,
			double _m3);
	RooDalitzHist(const RooDalitzHist& other, const char* name=0) ;
	virtual TObject* clone(const char* newname) const { return new RooDalitzHist(*this,newname); }
	inline virtual ~RooDalitzHist() { }
    
    virtual Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const;
	virtual Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const;

protected:

	RooRealProxy m12;
	RooRealProxy m23;
    TH2F *hist;
	const double mM;
	const double m1;
	const double m2;
	const double m3;

	Double_t evaluate() const;

private:

	ClassDef(RooDalitzHist,1) // Your description goes here...
};

#endif
