/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROODALITZDELAUNAY
#define ROODALITZDELAUNAY

#include "RooAbsPdf.h"
#include "TGraph2D.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooDalitzDelaunay : public RooAbsPdf {
public:
	RooDalitzDelaunay() :  graph(NULL), mM(0), m1(0), m2(0), m3(0) {} ;
	RooDalitzDelaunay(const char *name, const char *title,
			RooAbsReal& _m12,
			RooAbsReal& _m23,
            TGraph2D *_graph,
			double _mM,
			double _m1,
			double _m2,
			double _m3);
	RooDalitzDelaunay(const RooDalitzDelaunay& other, const char* name=0) ;
	virtual TObject* clone(const char* newname) const { return new RooDalitzDelaunay(*this,newname); }
	inline virtual ~RooDalitzDelaunay() { }
    
    virtual Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const;
	virtual Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const;

protected:

	RooRealProxy m12;
	RooRealProxy m23;
    TGraph2D *graph;
	const double mM;
	const double m1;
	const double m2;
	const double m3;

	Double_t evaluate() const;

private:

	ClassDef(RooDalitzDelaunay,1) // Your description goes here...
};

#endif
