/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROOFLATTE
#define ROOFLATTE

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooFlatte : public RooAbsPdf {
public:
	RooFlatte() : m_1a(0), m_1b(0), m_2a(0), m_2b(0), m_3a(0), m_3b(0), m1(0), m2(0) {} ;
	RooFlatte(const char *name, const char *title,
			RooAbsReal& _m,
			RooAbsReal& _mass_R,
			RooAbsReal& _g_1,
			RooAbsReal& _g_2,
			RooAbsReal& _g_3,
			double _m_1a,
			double _m_1b,
			double _m_2a,
			double _m_2b,
			double _m_3a,
			double _m_3b,
			double _m1,
			double _m2);
	RooFlatte(const RooFlatte& other, const char* name=0) ;
	virtual TObject* clone(const char* newname) const { return new RooFlatte(*this,newname); }
	inline virtual ~RooFlatte() { }

	double CalculateMomentum(const double m) const;

protected:

	RooRealProxy m;
	RooRealProxy mass_R;
	RooRealProxy g_1;
	RooRealProxy g_2;
	RooRealProxy g_3;
	const double m_1a;
	const double m_1b;
	const double m_2a;
	const double m_2b;
	const double m_3a;
	const double m_3b;
	const double m1;
	const double m2;

	Double_t evaluate() const;

private:

	ClassDef(RooFlatte,1) // Your description goes here...
};

#endif
