/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROOFLATTEANDNONRES
#define ROOFLATTEANDNONRES

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooFlatteAndNonRes : public RooAbsPdf {
public:
	RooFlatteAndNonRes() : m_1a(0), m_1b(0), m_2a(0), m_2b(0), m_3a(0), m_3b(0), m1(0), m2(0), m3(0), mM(0) {} ;
	RooFlatteAndNonRes(const char *name, const char *title,
			RooAbsReal& _m,
			RooAbsReal& _amp_flatte,
			RooAbsReal& _phase_flatte,
			RooAbsReal& _mass_R,
			RooAbsReal& _g_1,
			RooAbsReal& _g_2,
			RooAbsReal& _g_3,
			RooAbsReal& _amp_nonres,
			RooAbsReal& _phase_nonres,
			double _m_1a,
			double _m_1b,
			double _m_2a,
			double _m_2b,
			double _m_3a,
			double _m_3b,
			double _m1,
			double _m2,
			double _m3,
			double _mM);
	RooFlatteAndNonRes(const RooFlatteAndNonRes& other, const char* name=0) ;
	virtual TObject* clone(const char* newname) const { return new RooFlatteAndNonRes(*this,newname); }
	inline virtual ~RooFlatteAndNonRes() { }

	double CalculateMomentum(const double m) const;

protected:

	RooRealProxy m;
	RooRealProxy amp_flatte;
	RooRealProxy phase_flatte;
	RooRealProxy mass_R;
	RooRealProxy g_1;
	RooRealProxy g_2;
	RooRealProxy g_3;
	RooRealProxy amp_nonres;
	RooRealProxy phase_nonres;
	const double m_1a;
	const double m_1b;
	const double m_2a;
	const double m_2b;
	const double m_3a;
	const double m_3b;
	const double m1;
	const double m2;
	const double m3;
	const double mM;

	Double_t evaluate() const;

private:

	ClassDef(RooFlatteAndNonRes,1) // Your description goes here...
};

#endif
