/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROOSTUDENTSTDISTRIBUTION
#define ROOSTUDENTSTDISTRIBUTION

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooStudentsTDistribution : public RooAbsPdf {
public:
	RooStudentsTDistribution() {};
	RooStudentsTDistribution(const char *name, const char *title,
			RooAbsReal& _x,
			RooAbsReal& _mu,
			RooAbsReal& _sigma,
			RooAbsReal& _nu);
	RooStudentsTDistribution(const RooStudentsTDistribution& other, const char* name=0);
	virtual TObject* clone(const char* newname) const { return new RooStudentsTDistribution(*this,newname); }
	inline virtual ~RooStudentsTDistribution() { }

	Double_t get_mean() const;
	Double_t get_variance() const;

protected:

	RooRealProxy x;
	RooRealProxy mu;
	RooRealProxy sigma;
	RooRealProxy nu;

	Double_t evaluate() const;

private:

	ClassDef(RooStudentsTDistribution,1) // Your description goes here...
};

#endif
