/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROOTHREEBODYPHASESPACEPROJECTION
#define ROOTHREEBODYPHASESPACEPROJECTION

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooThreeBodyPhaseSpaceProjection : public RooAbsPdf {
public:
	RooThreeBodyPhaseSpaceProjection() : m1(0), m2(0), m3(0), mM(0) {};
	RooThreeBodyPhaseSpaceProjection(const char *name, const char *title,
			RooAbsReal& _m12,
			double _m1,
			double _m2,
			double _m3,
			double _mM);
	RooThreeBodyPhaseSpaceProjection(const RooThreeBodyPhaseSpaceProjection& other, const char* name=0);
	virtual TObject* clone(const char* newname) const {
		return new RooThreeBodyPhaseSpaceProjection(*this,newname);
	}
	inline virtual ~RooThreeBodyPhaseSpaceProjection() { }

protected:

	RooRealProxy m12;
	const double m1;
	const double m2;
	const double m3;
	const double mM;

	Double_t evaluate() const ;

private:

	ClassDef(RooThreeBodyPhaseSpaceProjection,1) // Your description goes here...
};

#endif
