/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROOTWOBODYTHRESHOLDFUNCTION
#define ROOTWOBODYTHRESHOLDFUNCTION

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooTwoBodyThresholdFunction : public RooAbsPdf {
public:
	RooTwoBodyThresholdFunction() : m_min(0) {} ;
	RooTwoBodyThresholdFunction(const char *name, const char *title,
			RooAbsReal& _m,
			RooAbsReal& _a,
			double _m_min);
	RooTwoBodyThresholdFunction(const RooTwoBodyThresholdFunction& other, const char* name=0) ;
	virtual TObject* clone(const char* newname) const { return new RooTwoBodyThresholdFunction(*this,newname); }
	inline virtual ~RooTwoBodyThresholdFunction() { }

protected:

	RooRealProxy m;
	RooRealProxy a;
	const double m_min;

	Double_t evaluate() const;

private:

	ClassDef(RooTwoBodyThresholdFunction,1) // Your description goes here...
};

#endif
