/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooThreeBodyPhaseSpaceProjection.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h"
#include "libComplexPDF/libComplexPDF.h"

ClassImp(RooThreeBodyPhaseSpaceProjection) 

RooThreeBodyPhaseSpaceProjection::RooThreeBodyPhaseSpaceProjection(const char *name, const char *title,
		RooAbsReal& _m12,
		double _m1,
		double _m2,
		double _m3,
		double _mM) :
		RooAbsPdf(name,title),
		m12("m12","m12",this,_m12),
		m1(_m1),
		m2(_m2),
		m3(_m3),
		mM(_mM) {
}

RooThreeBodyPhaseSpaceProjection::RooThreeBodyPhaseSpaceProjection(const RooThreeBodyPhaseSpaceProjection& other, const char* name) :
	   RooAbsPdf(other,name),
	   m12("m12",this,other.m12),
	   m1(other.m1),
	   m2(other.m2),
	   m3(other.m3),
	   mM(other.mM) {
}

Double_t RooThreeBodyPhaseSpaceProjection::evaluate() const {
	if(m12 < (m1+m2) || m12 > (mM-m3)) {
		return 0.0;
	} else {
		return ComplexPDF::ThreeBodyPhaseSpaceProjection(m12,mM,m1,m2,m3);
	}
}
