/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooTwoBodyThresholdFunction.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h"
#include "libComplexPDF/libComplexPDF.h"

ClassImp(RooTwoBodyThresholdFunction) 

RooTwoBodyThresholdFunction::RooTwoBodyThresholdFunction(const char *name, const char *title,
		RooAbsReal& _m,
		RooAbsReal& _a,
		double _m_min) :
		RooAbsPdf(name,title),
		m("m","m",this,_m),
		a("a","a",this,_a),
		m_min(_m_min) {
}

RooTwoBodyThresholdFunction::RooTwoBodyThresholdFunction(const RooTwoBodyThresholdFunction& other, const char* name) :
		   RooAbsPdf(other,name),
		   m("m",this,other.m),
		   a("a",this,other.a),
		   m_min(other.m_min) {
}

Double_t RooTwoBodyThresholdFunction::evaluate() const {
	return ComplexPDF::TwoBodyThresholdFunction(m,a,m_min);
}
