/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROOVARIANCEGAMMADISTRIBUTION
#define ROOVARIANCEGAMMADISTRIBUTION

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooVarianceGammaDistribution : public RooAbsPdf {
public:
	RooVarianceGammaDistribution() {};
	RooVarianceGammaDistribution(const char *name, const char *title,
			RooAbsReal& _x,
			RooAbsReal& _mu,
			RooAbsReal& _alpha,
			RooAbsReal& _beta,
			RooAbsReal& _lambda);
	RooVarianceGammaDistribution(const RooVarianceGammaDistribution& other, const char* name=0);
	virtual TObject* clone(const char* newname) const {
		return new RooVarianceGammaDistribution(*this,newname);
	}
	inline virtual ~RooVarianceGammaDistribution() { };

	Double_t get_mean() const;
	Double_t get_variance() const;

protected:

	RooRealProxy x;
	RooRealProxy mu;
	RooRealProxy alpha;
	RooRealProxy beta;
	RooRealProxy lambda;

	Double_t evaluate() const;

private:

	ClassDef(RooVarianceGammaDistribution,1) // Your description goes here...
};

#endif
